all:
	g++ -std=c++11 -Wall -c -o modulus.o modulus.cpp

	g++ -std=c++11 -Wall -c -o ligadoraux.o ligadoraux.cpp

	g++ -std=c++11 -Wall -c -o ligador.o ligador.cpp

	g++ -std=c++11 -Wall -o ligador modulus.o ligadoraux.o ligador.o
